### ISSUE TITLE
Custom STAR command?

### ISSUE THREAD

**Issue by borshago** [grexor/apa#12]
Hi,

I would like to use the apa pipeline with a modified STAR alignment step. I have trouble finding the pieces of apa code that are used to pass command line arguments to STAR. Could you point out the lines of code I have to modify to do this? Thanks!

-Daniel

**Comment by grexor** [comment]
Hello Daniel,

apa uses another python module (pybio), please look here at the file that contains parameters:

https://github.com/grexor/pybio/blob/master/bin/pybio.star

Hope this helps,
Gregor

**Comment by borshago** [comment]
Ah, there it is. Thanks!

Best,
Daniel
