### ISSUE TITLE
Missing proximal_pas -column entries in pairs_de.tab

### ISSUE THREAD

**Issue by borshago** [grexor/apa#14]
Hi,

I ran the apa workflow using the most recent master branch (for python3). After running the comps module with dexseq, I get the output file elib.pairs_de.tab. Some lines lack entries for the column "proximal_pas", and this messes with the structure of the file: these lines are shifted column-wise to the left, i.e. they have the "proximal_feature" -column entry (e.g. "utr3") in the "proximal_pas" column.

Is the lack of proximal_pas expected for some genes? Any ideas on how to properly format the elib.pairs_de.tab during the run of the comps module?

Best,
Daniel

**Comment by grexor** [comment]
Hi Daniel, no this is a big and should not happen, could you write more? Are you processing your own data?

**Comment by borshago** [comment]
Hi,

Regarding the shifting of entries, it seemed that I had a problem in my own downstream file reading. The file structure is fine after reanalysis. However, there are some missing entries for "proximal_pas" and "distal_pas" columns. Does this just mean that the site motif is unknown?

I'm running the apa workflow with python 3.7.6 on four samples:

https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e1.fastq.bz2
https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e2.fastq.bz2
https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e3.fastq.bz2
https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e4.fastq.bz2

Samples 1 and 2 were marked control, 3 and 4 test.

The file elib.pairs_de.tab can be downloaded from here: https://drive.google.com/open?id=1oOpcXTH7qusRiv4ZySzyKgxs7MaYnXAF.

**Comment by grexor** [comment]
Closing this issue for now, please try with the Docker example, should work as expected (see main repo page with docs), Cheers, Gregor
