### ISSUE TITLE
software->polyar installation

### ISSUE THREAD

**Issue by aparajitadutta** [grexor/apa#17]
Hi Gregor,

In your recent apa documentation, I could not find any mention regarding installation of polyar however I see that the polya module requires classification of the polyA sites through polyar software. Can you please let me know if it is required and it would be helpful if you can share the correct link to download/install it from.

cub.comsats.edu.pk/polyapredict.htm link provided by you in a previous issue does not seem to be working right now.

Regards,
Aparajita

**Comment by grexor** [comment]
Hi Aparajita,

You are working with mouse/human data? I would suggest you don't construct a polyA db (for which polyAR would be used) and that you use the polyAsite instead (https://polyasite.unibas.ch/).

Hope this helps,
Gregor

**Comment by aparajitadutta** [comment]
I am using human data (Ensembl98).

I am sorry if it is obvious and I am missing out, but it will be helpful if you can let me know the relevant files/modules that classifies based on polyAsite. 

Currently I am going by your documentation which calls for the process function in apa/polya. 'Process' by default 'annotates', which creates the polyA db which in turn classifies through polyAR.

**Comment by grexor** [comment]
You can skip the annotation and creation of polyA part completely, the idea is to download the polyAsite database (bedGraph format) and provide it to apa in all steps of analysis (you can store it in apa/data.polya). Sorry about the lack of docs still, I am in the process of making a docker instance with examples etc.
