### ISSUE TITLE
comps dexseq related queries

### ISSUE THREAD

**Issue by aparajitadutta** [grexor/apa#18]
Hi Gregor,

I am able to generate successfully the expression bed files as suggested in your documentation.

Next I want to get the list of differentially expressed polyA sites using dexseq. I am quite new to this. I have a few queries.

1. I see that different experiments have generated expression bed files with different set of polyA sites. Do you consider only the common polyA sites across all experiments for the dexseq analysis?
2. As per dexSeq documentation, dexSeq tool requires a flattened annotation file as input to "DEXSeqDataSetFromHTSeq" command. I do not see this being used in your dexseq implementation in "comps_dex.R" file.

Regards,
Aparajita

**Comment by grexor** [comment]
Shortly, 1) whichever polyA database is used (polyAsite, or generated from your experimental data) is then read in and the "expression" (counts) for each polyA site for each experiment is computed, 2) pybio repo actually creates a "linear" annotation from a GTF file (Ensembl hg38, mm10 etc.), hope this helps, Gregor
