### ISSUE TITLE
bed_expression_lexfwd does not normalize data

### ISSUE THREAD

**Issue by aparajitadutta** [grexor/apa#19]
Hi Gregor, 

Happy new year! 

In apa/bed init script I see that "bed_expression_lexrev" does the e.norm() for normalization (cpm) while this normalization is missing in other functions like "bed_expression_lexfwd"...

Any particular reason for normalizing the data only in case of "bed_expression_lexrev"?

Regards.

**Comment by grexor** [comment]
Hello aparajitadutta,

Sorry for the late reply, this normalization is for display purposes only, we do not use the normalized data in any analysis. Will add the normalization to lex_fwd to be consistent,

Cheers,
Gregor
