### ISSUE TITLE
apa examples not found

### ISSUE THREAD

**Issue by sambamba** [grexor/apa#20]
Hi,
Has the apa examples been relocated or removed? 

--2021-07-10 00:20:11--  https://expressrna.org/share/data/example/e1/example_e1.fastq.gz
Resolving expressrna.org (expressrna.org)... 94.130.134.178
Connecting to expressrna.org (expressrna.org)|94.130.134.178|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-10 00:20:12 ERROR 404: Not Found.

Thanks.

**Comment by grexor** [comment]
Fixed now. Was missing due to move reorganization of the server and the repositories. Please let me know if you encounter any other issues. Thanks!
