### ISSUE TITLE
https://expressrna.org/share/comps/example/example.config -- not found

### ISSUE THREAD

**Issue by sambamba** [grexor/apa#21]
Hi,
I received an error message when running the example.sh.

2021-07-12 10:30:59 (6.35 MB/s) - 'annotation.tab' saved [273/273]
/example/example.config: No such file or directory

Thanks.

**Comment by grexor** [comment]
Should be fixed now, was a permission problem with `run_apauser.sh`, Cheers, Gregor

**Comment by grexor** [comment]
Closing this issue for now, re-open or make another one please if further problems arise. Thanks!

**Comment by sambamba** [comment]
Many thanks.
