### ISSUE TITLE
One-to-one comparison with no replicate

### ISSUE THREAD

**Issue by yzhan360** [grexor/apa#22]
Hi, thanks for providing this apa tool. My question is can I compute comparative analysis on a one-to-one based comparison when I don't have any replicate? 

I am thinking to use EBseq to compute genes and sites to get differentially expression genes and sites. But how can I go to the differentially expressed site pairs?

Looking forward to hearing your thoughts.

**Comment by grexor** [comment]
Time passes fast :) please keep watching this repo and expressRNA, the one-to-one comparison without replicates will also be implemented however is not suggested (much better to have replicates).
