### ISSUE TITLE
software -> polyar, in class polya

### ISSUE THREAD

**Issue by nicokrez** [grexor/apa#9]
Dear Gregor,

this is my first issue report on github, I hope the form is okay, if not please correct me. 

I am getting an error message due to "polyar".

Error: Could not find or load main class polyar
Traceback (most recent call last):
  File "apa.polya", line 12, in <module>
    apa.polya.process(args.poly_id, map_id=args.map_id)
  File "/media/mdhdd/tools/apa/apa/polya/__init__.py", line 95, in process
    annotate(poly_id)
  File "/media/mdhdd/tools/apa/apa/polya/__init__.py", line 183, in annotate
    classify_polya(poly_id)
  File "/media/mdhdd/tools/apa/apa/polya/__init__.py", line 205, in classify_polya
    f = open("%s.res" % poly_id, "rt")
IOError: [Errno 2] No such file or directory: 'hg19.res'

I think the problem is "Error: Could not find or load main class polyar".
Did I mistakes during the installation?
Do you have any suggestions how to fix this?

Kind regards,
Nicolas

**Comment by grexor** [comment]
Dear Nicolas,

thank you for trying out apa. Looking at the trace, i think the problem is that polyar is missing, please download it from:

http://cub.comsats.edu.pk/polyapredict.htm

Sorry for the dependencies pages being incomplete / still missing, i will provide install instructions shortly. Meanwhile, please don't hesitate to contact me or post other issues here.

Thank you,
Gregor

**Comment by nicokrez** [comment]
Dear Gregor,

thank you very much for your fast response.
It worked, I got further with the analysis, but now I have the next error message:

Traceback (most recent call last):
  File "apa.polya", line 12, in <module>
    apa.polya.process(args.poly_id, map_id=args.map_id)
  File "/media/mdhdd/tools/apa/apa/polya/__init__.py", line 95, in process
    annotate(poly_id)
  File "/media/mdhdd/tools/apa/apa/polya/__init__.py", line 183, in annotate
    classify_polya(poly_id)
  File "/media/mdhdd/tools/apa/apa/polya/__init__.py", line 244, in classify_polya
    chr, strand, pos, gene_id, gene_name, interval, cDNA, seq = r[0], r[1], int(r[2]), r[3], r[4], r[5], float(r[6]), r[10]
ValueError: could not convert string to float: 



Maybe I have to many missing values in the hg19.tab?


==> ../polyar/hg19.tab <==
chr	strand	pos	gene_id	gene_name	interval	cDNA	pas_type	pas_loci	cs_loci	seq_-100_100
1	+	1630531				36.0	noclass			CAGTGCGGCCACGGCGCATGCGCCCCCTGCGGCTCCGCGCTCAGCGCCTGCCCCATCTGCCGCCAGCCCATCCGCGACCGCATCCAGATCTTCGTGTGAGCCGCGCCGTCCGCCGCGCCCGAGCTGCCTTCGCGTGCCCCCGCCCTGTGTTTTATAAAAAGAAAGATTCTCGGACGTTGCCTCTGCTGTCTGCCTGGGGGA
1	+	2352069				39.0	noclass			CAGTAGGCATGCCCCCTCCAGGAATGAGACCCCCTCCACCAGGAATTAGAGGTCCACCTCCCCTAGGAATGAGTCCACCAAGACCCTAGCATACTGTTGATCCATCTCAGTCACTTTTTCCCCTGCAATGTGTCTTGTGAAATTGTGTAGAGTGTTTGTGAGCTTTTTGTCCCCTGGTTCTGCATTAATAATAGCTAATAA


Kind regards,
Nicolas

**Comment by grexor** [comment]
Hi Nicolas,

could you check the resulting ".res" file (this is where the polyar results are read from), meanwhile i am also checking this out,

Thanks,
Gregor

**Comment by nicokrez** [comment]
Hi Gregor,

here is the output:

nico@tyan64:/media/mdhdd/tools/apa$ head -n 50 ../polyar/hg19.res 
POLYAR program
Search for mRNA 3'-end processing [Cleavage/poly(A)] sites 
Release 1.0
CIIT, Islamabad , Pakistan
____________________________________________________________________

Search option: PAS-strong & PAS-weak & PAS-less poly(A) sites
OUTPUT  Format: 
          PAS : Polyadenylation Signal
           CS :  Cleavage/poly(A) Site
            W : Integral Score 
____________________________________________________________________


>Query Name : >+1:1630531
     Length : 201

Cleavage/poly(A) sites not found
____________________________________________________________________
>Query Name : >+1:2352069
     Length : 201

Cleavage/poly(A) sites not found
____________________________________________________________________
>Query Name : >+1:2403303
     Length : 201

Cleavage/poly(A) sites not found
____________________________________________________________________
>Query Name : >+1:2403750
     Length : 201
PAS-weak CS/poly(A) sites: 1
 1	 CS:  101	 PAS:  79	 W: 42.31

Totally found: 1 Cleavage/poly(A) sites


Kind regards,
Nicolas

**Comment by grexor** [comment]
Hi Nicholas,

could you check if polyar is run? Unf., for now the software needs to be installed into:

$HOME/software/polyar

and is then run in the same folder. If you have some time, you could code a variable in the "config" module to include the path to polyar.

Search for this part in polya/__init__.py:

os.path.join(os.getenv("HOME"), "software/polyar/"

Hope this helps,
Cheers,
Gregor

**Comment by nicokrez** [comment]
Hi Gregor,

maybe I am wrong, but I think polyar is running, in my previous post I postet the output of polyar.

Here is the code to call polyar in your script:
    os.system("java polyar -i %s -o %s.res" % (polyadb_fasta, poly_id))

-o is  the output, hence the ".res" file is the output of polyar.


The error occurs when processing the ".tab " filr which has now information after running polyar:

==> ../polyar/hg19.tab <==
chr	strand	pos	gene_id	gene_name	interval	cDNA	pas_type	pas_loci	cs_loci	seq_-100_100
1	+	1630531				36.0	noclass			CAGTGCGGCCACGGCGCATGCGCCCCCTGCGGCTCCGCGCTCAGCGCCTGCCCCATCTGCCGCCAGCCCATCCGCGACCGCATCCAGATCTTCGTGTGAGCCGCGCCGTCCGCCGCGCCCGAGCTGCCTTCGCGTGCCCCCGCCCTGTGTTTTATAAAAAGAAAGATTCTCGGACGTTGCCTCTGCTGTCTGCCTGGGGGA
1	+	2352069				39.0	noclass			CAGTAGGCATGCCCCCTCCAGGAATGAGACCCCCTCCACCAGGAATTAGAGGTCCACCTCCCCTAGGAATGAGTCCACCAAGACCCTAGCATACTGTTGATCCATCTCAGTCACTTTTTCCCCTGCAATGTGTCTTGTGAAATTGTGTAGAGTGTTTGTGAGCTTTTTGTCCCCTGGTTCTGCATTAATAATAGCTAATAA
1	+	2403303				22.0	noclass			GTAGTTGATTACGAGGGAGTCAAATTTTCTTTTTAAAAAGGAGCTTCAATGATTTGTAACTGAAATATCAGGTTCTAGAAGAAACTGGCGCTTAAACCAAATCGCATGGATTTCTTTTTCAGTGACGTTCAAGTGTTTCTCACGGATGGAATTCTAGTCAGCTGCAGGCGGGAAGCCAGGCGGGTGGAGCCCATGGGAGCA
1	+	2403750				115.0	weak	-21	1	ATGTTTAAAGTTGGCCTCTATCCTAATGACTCAAAACTTGGTTCTTAACTACCATGATTGCTTTTGAGGGCCCGGAATTATAAATATATATTATATTTTAATTGTTTGAGATTATTTTGACACATTTCTTTGATACGTAGAGTGTTTTGTTTTTAATTTAAATCTGTCCTCATGCAACCCTCCATGAGGGGCAGCGAAGCT
1	+	3598737				15.0	noclass			TGCAGCCAGCACCAGCCCACACGGGCTCCAACGCTGGGGAGCTGGTTCACGCAGGGCGGGGGTCGTCATGGTAACGAGCCCCCCCCCCCCCCCCGGGGCCCACTCCTCTGCCTTCTGCAGCCACCAGCTCACAGTGGAGGCCACGGCTCAGGGAGTGTGGGCCTGGCAGGAGGGACCTGAGCGGCAGCTCCACCCTCAGAG
1	+	3775930				41.0	noclass			CGCCATGAAGGTGCTGGGCGGCGTGGCCCTCTTCTGGATCATCTTCATCCTGGGCTACCTCACAGGCTACTATGTGCACAAGTGCAAATAAATGCTGCCCCGCATGCACGCGGGGGGCTGGCCGCACACGTGAGAGCACAGGCCTGGAGACACACCCCTTGTACACATGGACCCCCCCACAGACACGGACCCTGCGGCACA
1	+	6623987				69.0	strong	-20	1	ATCGTTTACATGGTTCTGTGTAATTTTAAAGTTTATGTGTATAAAGCGAAGCTGTTTCTGTGAAACTGTATATTTTGTAAATAAATATATTGCTACTTTGAGGTTCATGATTCAAGGTTCAGGCGATTGCGTTCTGTGCTGAAGGACAATTGTGTTTCTTTTCTCCTTGCTACCTCCCCAAAGCATGATTACATCAAGTCT
1	+	7769703				151.0	strong	-23	1	ACCATGCAAAATGTTTTGAATTGCCCTTAAAATATGGAAAATGTTTTCTGAATGCTTTATATTCTTTCTGCTGTAAATTAAAAATGAAGAAAATTTCCCCATACTACGTGTGTGTTTTGCTTTAATATGACCGGGTAGTGAAATCTAAGGTGATGGGCACATGTTTCAAAACATATGTAATAATGTCAAGGATTTCCTTCT
1	+	8865433				19.0	noclass			CGAGATGTACCTGCTGGGGTCATCGGGAGACTTGAAGTCCAGGTCATACTTCCCAGACCTGAAGAACTCGGAGGCCGCTACGTCCATGCCGATGACCACCTTATCAGTGTAGCCAGCTTTCCCAATAGCAGTCTTCAGCAGCTCCAGGCCTGGGAAGAGATGGTGACAACAGGTTTGGAAAACAGGTAGGTACAGAGAAAA


Here again the important part of the error message:
in classify_polya
    chr, strand, pos, gene_id, gene_name, interval, cDNA, seq = r[0], r[1], int(r[2]), r[3], r[4], r[5], float(r[6]), r[10]
ValueError: could not convert string to float: 

Cheers,
Nicolas

**Comment by grexor** [comment]
Hi Nicolas,

it seems something goes wrong for you in writting the .tab file, can you check that it has this kind of structure:

ftab.write("\t".join(["chr", "strand", "pos", "gene_id", "gene_name", "interval", "cDNA", "pas_type", "pas_loci", "cs_loci", "seq_-100_100"]) + "\n")

Then you should be able to read it back with:

chr, strand, pos, gene_id, gene_name, interval, cDNA, seq = r[0], r[1], int(r[2]), r[3], r[4], r[5], float(r[6]), r[10]

Thanks,
Gregor
